name: Close stale PRs

on:
  schedule:
    # Run daily at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  stale-prs:
    uses: lafourchette/github-actions/.github/workflows/stale-prs.yml@v1
